package solution

func trailingZeroes(n int) int {
	// this problem is so boting
	// I can observe trailing 0 are generated by 2 and 5
	// then just find out how many 5 and 2 in a given number
	// but I guess There must be a mathematic mathod to calculate the result directly...
	// but what we called algorithm is solution to handle some problem that hardly be calculated by mathematic methods...
	if n <= 2 {
		return 0
	}
	n5 := 0
	n2 := 0

	for i := 2; i <= n; i++ {
		n5_, n2_ := getCnts(i)
		n5 += n5_
		n2 += n2_
	}

	if n5 > n2 {
		return n2
	}
	return n5
}

func getCnts(n int) (int, int) {
	current := n
	n5 := 0
	n2 := 0
	for current/5 > 0 {
		n5++
		current /= 5
	}
	current = n
	for current/2 > 0 {
		n2++
		current /= 2
	}
	return n5, n2
}
